version: '3'

services:
    rabbitmq:
        build: ./rabbit
        ports:
            - 15672:15672
            - 61613:61613
        networks:
            - web

    node1:
        build: ./
        ports:
            - 8080:8080
        networks:
            - web

    node2:
        build: ./
        ports:
            - 8081:8080
        networks:
            - web

    node3:
        build: ./
        ports:
            - 8082:8080
        networks:
            - web

networks:
    web:
        driver: bridge

volumes:
    rabbitmq_data:
        driver: local
